# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [75]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [98]:
A = np.arange(1, 16).reshape(3,5)

In [99]:
print(f'Dimensions in A: {A.ndim}')
print(f'Shape of A: {A.shape}')
print(f'Size of A: {A.size}')
print(f'Datatype of A: {type(A)}')

Dimensions in A: 2
Shape of A: (3, 5)
Size of A: 15
Datatype of A: <class 'numpy.ndarray'>


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [100]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [101]:
print('B-C')
print(B-C)
print('\nB*C')
print(B*C)
print('\nB@C')
print(B@C)

B-C
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

B*C
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

B@C
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [102]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [103]:
print('B exponentiated:')
print(np.exp(B))
print(f'Minimum value of B: {B.min()}')
print(f'Minimum value of each row of B: {B.min(axis=1)}')
print(f'Minimum value of each column of B: {B.min(axis=0)}')
print(f'Index of minimum value of B: {B.argmin()}')
print(f'Index of minimum value of each row of B: {B.argmin(axis=1)}')
print(f'Sum of all elements of B: {B.sum()}')
print(f'Mean of all elements of B: {B.mean()}')
print(f'Median of all elements of B: {np.median(B)}')

B exponentiated:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Minimum value of B: 1
Minimum value of each row of B: [1 4 7]
Minimum value of each column of B: [1 2 3]
Index of minimum value of B: 0
Index of minimum value of each row of B: [0 0 0]
Sum of all elements of B: 45
Mean of all elements of B: 5.0
Median of all elements of B: 5.0


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [104]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [105]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [115]:
print('If you slice with fewer indices than axes you will slice in the first dimension and get all elements from the second dimension')

If you slice with fewer indices than axes you will slice in the first dimension and get all elements from the second dimension


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [107]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [108]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [109]:
for i in A:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [120]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [125]:
print('Vi börjar med en endimensionell array med 30 element. Därefter vill vi skapa en 3-dimensionell array som innehåller lika många element som den ursprungliga.')
print('Vi vill att den första dimensionen har 2 element, den andra dimensionen har 3 element, och den tredje dimensionen har så många element som krävs för att det ska bli 30 element.')
print(f'Den nya arrayen (b) har då formen {b.shape}.')

Vi börjar med en endimensionell array med 30 element. Därefter vill vi skapa en 3-dimensionell array som innehåller lika många element som den ursprungliga.
Vi vill att den första dimensionen har 2 element, den andra dimensionen har 3 element, och den tredje dimensionen har så många element som krävs för att det ska bli 30 element.
Den nya arrayen (b) har då formen (2, 3, 5).


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [89]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [90]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [91]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [181]:
def add_mult_matrices(S, T, add_mult):
    if not isinstance(S, np.ndarray) or not isinstance(T, np.ndarray):
        return 'En eller båda av matrisargumenten är inte en matris.'
    if add_mult not in ('add','mult'):
        return 'Tredje argumentet är inte "add" eller "mult"'
    if add_mult == 'add':
        if S.shape == T.shape:
            return S+T
        else:
            return 'De två matriserna har inte samma dimension för matrisaddition'
    if add_mult == 'mult':
        if S.shape[1] == T.shape[0]:
            return S@T
        else:
            return 'Antalet kolumner i första matrisen är inte samma som antalet rader i andra matrisen för matrismultiplikation'

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [218]:
print('Uppgift 10.1.1')
x = np.array([4,3])
print(f'(a) x har dimensionen {x.shape}')
print(f'(b) 5x = {5*x}')
print(f'(c) 3x = {3*x}')
print(f'(d) 5x + 3x = {add_mult_matrices(5*x,3*x,'add')}')
print(f'(e) 8x = {8*x}')
print(f'(f) 4x - x = {add_mult_matrices(4*x,-x,'add')}')
print(f'(g) xT = {x.transpose().shape}')
print(f'(h) ')
print(f'(i) Normen av x är {np.linalg.norm(x)}')
print('Uppgift 10.1.2')
v = np.array([3,7,0,11])
print(f'(a) v har dimensionen {x.shape}')
print(f'(b) 2v = {2*v}')
print(f'(c) 5v + 2v = {add_mult_matrices(5*v,2*v,'add')}')
print(f'(d) 4v - 2v = {add_mult_matrices(4*v,-2*v,'add')}')
print(f'(e)')
print(f'(f) Normen av v är {np.linalg.norm(v)}')
print('Uppgift 10.1.3')
v1 = np.array([4,3,1,5])
v2 = np.array([2,3,1,1])
print(f'(a) Normen av v1 är {np.linalg.norm(v1)}')
print(f'(b) Normen av v1-v2 är {np.linalg.norm(add_mult_matrices(v1,-v2,'add'))}')


Uppgift 10.1.1
(a) x har dimensionen (2,)
(b) 5x = [20 15]
(c) 3x = [12  9]
(d) 5x + 3x = [32 24]
(e) 8x = [32 24]
(f) 4x - x = [12  9]
(g) xT = (2,)
(h) 
(i) Normen av x är 5.0
Uppgift 10.1.2
(a) v har dimensionen (2,)
(b) 2v = [ 6 14  0 22]
(c) 5v + 2v = [21 49  0 77]
(d) 4v - 2v = [ 6 14  0 22]
(e)
(f) Normen av v är 13.379088160259652
Uppgift 10.1.3
(a) Normen av v1 är 7.14142842854285
(b) Normen av v1-v2 är 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [233]:
A = np.array([[2, 1, -1],[1, -1, 1]])
B = np.array([[4, -2, 1],[2, -4, -2]])
C = np.array([[1, 2],[2, 1]])
D = np.array([[3, 4],[4, 3]])
E = np.array([[1],[2]])
I = np.array([[1, 0],[0, 1]])
print('Uppgift 10.2.1')
print(f'(a) 2A =\n{2*A}')
print(f'(b) B - 2A=\n{add_mult_matrices(B,-2*A,'add')}')
print(f'(c) 3C - 2E=\n{add_mult_matrices(3*C,-2*E,'add')}')
print(f'(d) 2D - 3C = \n{add_mult_matrices(2*D,-3*C,'add')}')
print(f'(e) DT - 2D =\n{add_mult_matrices(D.T,2*D,'add')}')
print(f'(f) 2CT - 2DT =\n{add_mult_matrices(2*C.T,-2*D.T,'add')}')
print(f'(g) AT - B =\n{add_mult_matrices(A.T,-1*B,'add')}')
print(f'(h) AC =\n{add_mult_matrices(A,C,'mult')}')
print(f'(h) CD =\n{add_mult_matrices(C,D,'mult')}')
print(f'(h) CB =\n{add_mult_matrices(C,B,'mult')}')
print(f'(h) CI =\n{add_mult_matrices(C,I,'mult')}')
print(f'(h) ABT =\n{add_mult_matrices(A,B.T,'mult')}')

Uppgift 10.2.1
(a) 2A =
[[ 4  2 -2]
 [ 2 -2  2]]
(b) B - 2A=
[[ 0 -4  3]
 [ 0 -2 -4]]
(c) 3C - 2E=
De två matriserna har inte samma dimension för matrisaddition
(d) 2D - 3C = 
[[3 2]
 [2 3]]
(e) DT - 2D =
[[ 9 12]
 [12  9]]
(f) 2CT - 2DT =
[[-4 -4]
 [-4 -4]]
(g) AT - B =
De två matriserna har inte samma dimension för matrisaddition
(h) AC =
Antalet kolumner i första matrisen är inte samma som antalet rader i andra matrisen för matrismultiplikation
(h) CD =
[[11 10]
 [10 11]]
(h) CB =
[[  8 -10  -3]
 [ 10  -8   0]]
(h) CI =
[[1 2]
 [2 1]]
(h) ABT =
[[5 2]
 [7 4]]


In [234]:
A = np.array([[2,3,4],[5,4,1]])
print('Uppgift 10.2.2')
print(f'AAT =\n{add_mult_matrices(A,A.T,'mult')}')

Uppgift 10.2.2
AAT =
[[29 26]
 [26 42]]


In [245]:
A = np.array([[1,2],[2,4]])
B = np.array([[2,1],[1,3]])
C = np.array([[4,3],[0,2]])
AB = add_mult_matrices(A,B,'mult')
AC = add_mult_matrices(A,C,'mult')
print('Uppgift 10.2.3')
print(f'AB =\n{AB}')
print(f'AC =\n{AC}')
print(f'AB = AC är {np.array_equal(AB,AC)}')
print(f'B = C är {np.array_equal(B,C)}')

Uppgift 10.2.3
AB =
[[ 4  7]
 [ 8 14]]
AC =
[[ 4  7]
 [ 8 14]]
AB = AC är True
B = C är False


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [92]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [93]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [94]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [246]:
print('Eftersom v2 är en view av v1 (och inte en kopia) så ändras även det sista elementet i v1 när vi ändrar i v2.')

Eftersom v2 är en view av v1 (och inte en kopia) så ändras även det sista elementet i v1 när vi ändrar i v2.
